print("Income tax calculater")
print("please declare your income(i) and tax percentage(p)")
i = input("income")
i = int(i)
p = input("tax percentage")
p = int(p)
x = i*(p/100)
print("amount of tax paid is")
print(x)